apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-dns-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-dns-role-cluster
subjects:
  - kind: ServiceAccount
    name: k8s-dns-account
    namespace: k8s-dns
