apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-dns-role-cluster
rules:
  # runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [""]
    resources: [services, namespaces]
    verbs: [get, list, watch]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [get, list, watch]
  # admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]
  # events
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  # app
  - apiGroups: [nathanv.me]
    resources: [dnsconfigs]
    verbs: [get, list, watch, patch, update]
