apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-dns-role
  namespace: k8s-dns
rules:
  # events
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  # app
  - apiGroups: [nathanv.me]
    resources: [dnsconfigs]
    verbs: [get, list, watch, patch, update]
