apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: k8s-dns-nathanv-me-crd
spec:
  group: nathanv.me
  # namespaced unique, not cluster unique
  scope: Namespaced
  names:
    plural: dnsconfigs
    singular: dnsconfig
    kind: DNSConfig
  versions:
  - name: v1
    # required
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              hostname:
                type: string
                description: The hostname of the record(s) to create.
              internalCNAME:
                type: string
                description: For the internal DNS record, what the value of the target of the CNAME record should be. Cannot be combined with `internalService`.
              internalService:
                type: string
                description: For the internal DNS record, what service should be used as the target of the A record should be. Must exist in the same namespace. Cannot be combined with `internalCNAME`.
              externalCNAME:
                type: string
                description: If an external DNS record should be created, what the value of the target of the CNAME record should be.
            required:
              - hostname
            oneOf:
              - required:
                  - internalCNAME
              - required:
                  - internalService